### ISSUE TITLE
Add integration with Multi-configuration (matrix) project type

### ISSUE THREAD

**Issue by OndrejKotek** [jenkinsci/cachet-gating-plugin#13] opened 2019-07-25 13:22 UTC
The plugin could take names of required resources from project axes and check them for (runs of) individual configurations.

For example, having one axis of a job populated by database names, when one of the DBs is not available, I would expect that configurations using the available DBs are executed while configurations with the unavailable DB are held in queue.

**Comment by winklerm** [comment] 2019-09-02 13:52
+1 - this would be really useful for us as well. Any estimate if/when this issue could be planned for implementation? Thanks!

**Comment by Avielyo10** [comment] 2019-09-19 13:35
@winklerm @OndrejKotek 

Instead of using the old matrix job you can easily [create a Matrix-like flow with pipeline](https://support.cloudbees.com/hc/en-us/articles/115000088431-Create-a-Matrix-like-flow-with-Pipeline), what do you think?

**Comment by OndrejKotek** [comment] 2019-09-20 05:18
@Avielyo10 How to implement (re-)running just selected combinations, or matrix-reloaded plugin functionality? This is for free with matrix jobs.

**Comment by Avielyo10** [comment] 2019-09-24 07:19
@OndrejKotek You can get it with the following:
```groovy
def getTasks(axisNodes, axisTools) {
    def tasks = [:]
    for(int i=0; i< axisNodes.size(); i++) {
        def axisNodeValue = axisNodes[i]
        for(int j=0; j< axisTools.size(); j++) {
            def axisToolValue = axisTools[j]
            tasks["${axisNodeValue}/${axisToolValue}"] = {
                node(axisNodeValue) {
                    def javaHome = tool axisToolValue
                    println "Node=${env.NODE_NAME}"
                    println "Java=${javaHome}"
                    build job: 'template-test-job', parameters: [string(name: 'LABEL', value: 'a')]
                }
            }
        }
    }
    return tasks
}

pipeline {
    agent none

    stages {

        stage("Before") {
            agent any
            steps {
                echo "before"
            }
        }

        stage("Matrix") {
            steps {
                script {
                    def axisNodes = ["osx-agent-1","osx-agent-2"]
                    def axisTool = ["jdk7","jdk8"]
                    parallel getTasks(axisNodes, axisTool)
                }
            }
        }

        stage("After") {
            agent any
            steps {
                echo "after"
            }
        }
    }
}
```

**Comment by winklerm** [comment] 2019-09-24 08:08
@Avielyo10 thanks for the example! However, I am not sure if it solves the problem @OndrejKotek mentioned: we would like to be able to re-run selected combinations without modifying the pipeline source; for instance, when there are test failures caused by unstable infrastructure, etc. Please note that such unstability will not be typically handled by Cachet plugin, because it is caused by slow resources, not unavailable resources.

**Comment by OndrejKotek** [comment] 2019-09-24 08:34
@Avielyo10 I missed it in the first round, how does the cachet plugin check the individual parallel executions for availability of the given resource, for example a DB (see the issue description)?

**Comment by Avielyo10** [comment] 2019-11-19 19:12
You can now use it as follows(Job DSL):
```groovy
matrixJob('example') {
    axes {
       cachetAxis {
             name "cachet1"
             resources(["service1", "service2"])
       } 
       cachetAxis {
             name "cachet2"
             resources(["service3", "service4"])
       }
    }
}
```
Can we close the issue?

**Closed** 2020-03-06 11:12 UTC
